name: Build and release

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: https://git.broillet.ch/mathieu/pyinstaller-gitea-action@main
        with:
          python_ver: '3.12'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'spotidalyfin-${{ github.ref_name }}'
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*